export const currencySymbols: {[key:string]: string} = {
    AUD: '$',
    BGN: 'лв',
    BRL: 'R$',
    CHF: 'CHF',
    CAD: '$',
    CNY: '¥',
    CZK: 'Kč',
    DKK: 'kr',
    EUR: '€',
    GBP: '£',
    HKD: '$',
    HRK: 'kn',
    HUF: 'Ft',
    IDR: 'Rp',
    ILS: '₪',
    INR: 'INR',
    ISK: 'kr',
    JPY: '¥',
    KRW: '₩',
    MXN: '$',
    MYR: 'RM',
    NOK: 'kr',
    NZD: '$',
    PHP: '₱',
    PLN: 'zł',
    RON: 'lei',
    RUB: '₽',
    SEK: 'kr',
    SGD: '$',
    THB: '฿',
    TRY: 'TRY',
    USD: '$',
    ZAR: 'R',
}

export enum SessionStorageKeys {
    CORRENCIES = 'correncies',
    COVERTED_HISTORY = 'converted_history'
}